from .nodes.translate_universal import (
    NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS
)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS"
]

from .nodes.amd_monitor import NODE_CLASS_MAPPINGS as AMD_MONITOR_MAPPINGS
from .nodes.amd_monitor import NODE_DISPLAY_NAME_MAPPINGS as AMD_MONITOR_DISPLAY

NODE_CLASS_MAPPINGS.update(AMD_MONITOR_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AMD_MONITOR_DISPLAY)