from .nodes.translate_universal import (
    NODE_CLASS_MAPPINGS as TRANSLATE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TRANSLATE_DISPLAY
)

from .nodes.amd_monitor import (
    NODE_CLASS_MAPPINGS as AMD_MONITOR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AMD_MONITOR_DISPLAY
)

from .nodes.amd_monitor import (
    NODE_CLASS_MAPPINGS as AMD_MONITOR_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as AMD_MONITOR_DISPLAY
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(TRANSLATE_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TRANSLATE_DISPLAY)

NODE_CLASS_MAPPINGS.update(AMD_MONITOR_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AMD_MONITOR_DISPLAY)
WEB_DIRECTORY = "./web"


__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS"
    "WEB_DIRECTORY"
]