from .translate_universal import (
    NODE_CLASS_MAPPINGS as _TRANSLATE_UNIVERSAL_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _TRANSLATE_UNIVERSAL_DISPLAY
)

from .bangtrix_simple_translate import (
    NODE_CLASS_MAPPINGS as _SIMPLE_TRANSLATE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _SIMPLE_TRANSLATE_DISPLAY
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(_TRANSLATE_UNIVERSAL_MAPPINGS)
NODE_CLASS_MAPPINGS.update(_SIMPLE_TRANSLATE_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(_TRANSLATE_UNIVERSAL_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(_SIMPLE_TRANSLATE_DISPLAY)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS"
]
