from .translate_universal import (
    NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS
)

from .amd_monitor import (
    NODE_CLASS_MAPPINGS as AMD_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as AMD_DISPLAY
)

# Gabungkan mappings
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **AMD_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **AMD_DISPLAY}

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS"
]